packages:
  - apps/*
  - libs/*
overrides:
  yargs-parser@>=6.0.0 <13.1.2: '>=13.1.2'
  got@<11.8.5: '>=11.8.5'
  semver-regex@<3.1.3: '>=3.1.3'
  semver-regex@<3.1.4: '>=3.1.4'
  trim-newlines@<3.0.1: '>=3.0.1'
  esbuild@<=0.24.2: '>=0.25.0'
  koa@<2.16.1: '>=2.16.1'
